### ISSUE TITLE
event listeners

### ISSUE THREAD

**Issue by mycaule** [joachimesque/mv-styleguide#1]
Hello thanks for your code sample,

I don't understand how the change handler gets called, there is no trace in my developer console.
https://github.com/joachimesque/mv-styleguide/blob/a0347a08c4d4af37a9b9fd798f6e83b8af86895c/script.js#L64

Currently I am doing this hack to track changes :
https://github.com/mycaule/portfolio/blob/master/index.html#L34
https://github.com/mycaule/portfolio/blob/master/app.js#L89

**Comment by joachimesque** [comment]
I have no precise recollection of coding this part of my code, and I forgot to document it. As far as I can recall, it's a part I added to test if the events were firing, and they didn't and I didn't investigate further… the whole script works without.

I should add that I'm not that good at JS, and I was hungover when I coded it, sorry about that :/

**Comment by mycaule** [comment]
Ok merci quand même !

**Comment by mycaule** [comment]
I looked at the source code, here is the correct event listener name to use if you need it in the future:
https://github.com/mavoweb/mavo/blob/master/src/expressions.js#L19-L40

```javascript
document.addEventListener('mv-change', function(event) { ...
  // the event object contains the details of what exactly changed
  // you can then do what you want depending on your case
  console.log(event.action, event.property, event.value)
})
```

It has been renamed in November in [this commit](https://github.com/mavoweb/mavo/commit/07e35d347105170a6c22a79da8f0600f51d07c07#diff-da32ca2a3b532455dd08ad277a27dd6a) so your application may be broken now since you haven't updated it since October.

**Comment by joachimesque** [comment]
Ooh yeah, thanks ! I'll give it a try :)

It works : https://github.com/joachimesque/mv-styleguide/blob/master/script.js
Thanks !
